export const POPULATE_PRODUCTS = "POPULATE_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
